nodeLinker: node-modules

# Prevent hoisting to maintain package isolation
nmHoistingLimits: workspaces

# Enable PnP for better dependency resolution
enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.9.2.cjs
