// This file is auto-generated by GitHub Actions after successful release
export const release = {
  production: "v0.0.21",
  downloads: {
    windows: "https://github.com/moughxyz/viberunner-releases/releases/download/v0.0.21/Viberunner-0.0.21.Setup.exe",
    macOS: {
      dmg: "https://github.com/moughxyz/viberunner-releases/releases/download/v0.0.21/Viberunner.dmg",
      arm64: "https://github.com/moughxyz/viberunner-releases/releases/download/v0.0.21/Viberunner-darwin-arm64-0.0.21.zip"
    },
    linux: {
      deb: "https://github.com/moughxyz/viberunner-releases/releases/download/v0.0.21/viberunner_0.0.21_amd64.deb",
      rpm: "https://github.com/moughxyz/viberunner-releases/releases/download/v0.0.21/viberunner-0.0.21-1.x86_64.rpm"
    }
  }
}
