// This file is auto-generated by the release script
export const release = {
  production: "v1.0.0",
  downloads: {
    windows: "https://github.com/moughxyz/viberunner/releases/download/v1.0.0/Viberunner-1.0.0.Setup.exe",
    macOS: {
      dmg: "https://github.com/moughxyz/viberunner/releases/download/v1.0.0/Viberunner.dmg",
      arm64: "https://github.com/moughxyz/viberunner/releases/download/v1.0.0/Viberunner-darwin-arm64-1.0.0.zip"
    },
    linux: {
      deb: "https://github.com/moughxyz/viberunner/releases/download/v1.0.0/viberunner_1.0.0_amd64.deb",
      rpm: "https://github.com/moughxyz/viberunner/releases/download/v1.0.0/viberunner-1.0.0-1.x86_64.rpm"
    }
  }
}