name: Pre-Release

on:
  push:
    tags:
      - 'v*-beta*'
      - 'v*-alpha*'
      - 'v*-rc*'
    paths:
      - 'packages/app/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/pre-release.yml'

jobs:
  build-and-prerelease:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-latest
            platform: win32
            arch: x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm ci --workspace=packages/app

    - name: Build renderer
      run: npm run build
      working-directory: packages/app

    - name: Make distributables
      run: npm run make
      working-directory: packages/app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: viberunner-${{ matrix.platform }}-${{ matrix.arch }}-prerelease
        path: |
          packages/app/out/make/**/*
        retention-days: 14

  create-prerelease:
    needs: build-and-prerelease
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Pre-Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Viberunner ${{ github.ref_name }} (Pre-Release)
        draft: false
        prerelease: true
        generate_release_notes: true
        body: |
          ## ⚠️ Pre-Release: Viberunner ${{ github.ref_name }}

          🧪 **This is a pre-release version for testing purposes.**

          **⚠️ Warning**: This version may contain bugs and is not recommended for production use.

          ### 📥 Download Instructions

          - **🍎 macOS**: Download the `.dmg` file for easy installation
          - **🪟 Windows**: Download the Setup `.exe` file for installation
          - **🐧 Linux**: Choose from `.deb` (Ubuntu/Debian) or `.rpm` (RHEL/Fedora)

          ### 🐛 Reporting Issues

          If you encounter any issues with this pre-release, please [open an issue](../../issues) with:
          - Your operating system and version
          - Steps to reproduce the problem
          - Expected vs actual behavior

          ---

          **Full Changelog**: [${{ github.event.before }}...${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }})
        files: |
          artifacts/**/*.dmg
          artifacts/**/*.zip
          artifacts/**/*.exe
          artifacts/**/*.deb
          artifacts/**/*.rpm
          artifacts/**/*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}